## Extension: Grid World

Consider a robot navigating in a grid-based environment. Each cell in the grid represents a distinct state of the surroundings. The robot can take four deterministic actions at each cell: "up," "down," "left," and "right," resulting in the robot to move precisely one cell in the corresponding direction on the grid. Actions that would take the agent off the grid are not allowed. Within the grid, certain states (orange) correspond to undesirable conditions, such as rough terrain, while one state (green) represents the ultimate goal.

Upon reaching the goal state, the robot gains a reward of 1. Conversely, traversing the rough terrain incurs a penalty (or negative reward) of 10. Additionally, every move the robot makes entails a penalty of 1. The robot's primary objective is to efficiently reach the goal state, aiming to maximize the total reward (minimize the total penalty) incurred. This entails both avoiding the rough terrain and efficiently navigating through the grid.

<img src="grid_world.png" alt="Image" width="300" height="300" />

In [1]:
import numpy as np

### Q1
Try to utilize dynamic programming algorithm to address the grid world problem.

### Answer:

To solve the grid world problem using dynamic programming, we can apply the **Value Iteration** algorithm. This method iteratively updates the value function for each state based on the expected rewards of possible actions.

**Steps:**

1. **Initialize Values:** Assign an initial value of zero to the value function of all states.

2. **Update Values:**  Apply Bellman's equation to update the value function:

$ V(s) \leftarrow \max_{a} \left[ \text{Reward}(s, a) + \gamma \cdot \sum_{s'} \text{Transition Probability}(s, a, s') \cdot V(s') \right]$

   Where:
   *  `V(s)` is the value of state `s`
   *  `maxₐ` denotes the maximum value over all possible actions `a`
   *  `Reward(s, a)` is the reward obtained by taking action `a` in state `s`
   *  `γ` is the discount factor
   *  `Σₛ'` represents the sum over all possible next states `s'`
   *  `Transition Probability(s, a, s')` is the probability of transitioning to state `s'` from state `s` when taking action `a`

3. **Convergence:** Repeat step 2 until the values converge. Convergence is achieved when the change in the value function between iterations is less than a predefined threshold (`θ`).


### Q2
What challenge or issue are you currently facing? Provide an explanation for the nature of this problem. In Practical 4, we will explore strategies to address this challenge.

### Answer:

**1. Speed of Convergence:**

* **Challenge:** Value iteration can converge slowly, especially in large or complex networks.
* **Explanation:** Convergence speed depends on the number of iterations needed to reach the threshold. Larger networks or those with intricate reward structures may require more iterations, leading to slower convergence.

**2. Handling Large Networks:**

* **Challenge:** Computational resources and time requirements increase significantly with network size.
* **Explanation:** As the network expands, the number of states and actions grows, demanding more computational power. This can result in higher memory usage and extended processing times.

**3. Accuracy and Threshold Management:**

* **Challenge:** Selecting the right convergence threshold (`θ`) is crucial for balancing computational efficiency and solution accuracy.
* **Explanation:** A high threshold might cause premature convergence, yielding a suboptimal solution. Conversely, a low threshold could demand excessive computation without guaranteeing optimality. Finding the optimal threshold is essential for efficient value iteration.


In [2]:
# Define the grid world as a matrix using np.array. Each entry correspond to its reward.
grid = np.array([
    [0, 0, -10, 0],
    [0, 0, 0, 0],
    [0, 0, -10, 0],
    [0, 0, -10, 1]
])

In [3]:
# Initialize the value function as a zero matrix with the same shape with the grid.
values = np.zeros_like(grid, dtype=float)

In [4]:
# Define the function to get next state. The action includes "up", "down", "left", "right".
def get_next_state(i, j, action):
  if action == "up":
      i -= 1
  elif action == "down":
      i += 1
  elif action == "left":
      j -= 1
  elif action == "right":
      j += 1
  return i, j

In [5]:
# Define the function to check if the next state is valid. The states beyond the grid are not valid. This function returns Boolean value.
def is_valid_state(i, j, grid):
  rows, cols = grid.shape
  return 0 <= i < rows and 0 <= j < cols

In [6]:
# Value Iteration Algorithm
theta = 0.01  # Convergence threshold
gamma = 0.9   # Discount factor

while True:
    delta = 0
    for i in range(grid.shape[0]):
        for j in range(grid.shape[1]):
            v = values[i, j]
            max_value = float('-inf')
            for action in ["up", "down", "left", "right"]:
                next_i, next_j = get_next_state(i, j, action)
                if is_valid_state(next_i, next_j, grid):
                    next_value = grid[next_i, next_j] + gamma * values[next_i, next_j]
                    max_value = max(max_value, next_value)
            values[i, j] = max_value
            delta = max(delta, abs(v - values[i, j]))
    if delta < theta:
        break

print("Optimal Values:\n", values)

Optimal Values:
 [[3.07063342 3.41967008 3.80670307 4.23603276]
 [3.41967008 3.80670307 4.23603276 4.71242949]
 [3.07770307 3.42603276 4.71242949 5.24118654]
 [2.76993276 3.08342949 5.24118654 4.71706788]]
